language: python
python:
- '2.7'
install:
  - git clone --depth 1 https://github.com/pythonjobs/template.git ../template
  - pip install -r ../template/requirements.txt
script: ../template/build.py .
after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && ../template/preview.py || false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ../template/deploy.py || false'
env:
  global:
    secure: "R3cyaiQAroQPGE2YeGB8r0pKn59zAXEURCqidWkIkfPbMrVgiUGwKxooOVLyFPm7Go9Mp749fGBFrw464Yh+3sk2J3SXqjTGUL151V/lFovhK1q3kgQDUipW+ZjpiURu7+cLvz6sxmvQNvpqLNrDtaBWJwVui1Nj0derk/NCPmI="
